language: rust

os:
  - linux
  - osx

rust:
  # someday, but rls relies on nightly right now.
  # - stable
  # - beta
  - nightly

before_install:
  - nvm install 8.1.4
  - rustup component add rustfmt-preview      

script:
  - cargo fmt -- --write-mode=diff
  - cd frontend && npm install && npm run prod && npm run test
  - cd .. && cargo build --all && cargo test --all
  - cargo run -- --manifest-path=example/Cargo.toml build
